version: "3.7"
services:
  firebase:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000 # Emulator Suite UI
      - 8080:8080 # Cloud Firestore
    command: bash
    tty: true
